name: pypocs
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - cupy
  - cusignal
  - pylops
  - numba
  - matplotlib
  - ipython
  - jupyterlab
  - tqdm
  - pip:
      - pyproximal
      - setuptools_scm
